project_id = "esrimjavbjdtecszxudc"

[api]
enabled = true

[functions.analyze-email-design]
verify_jwt = false

[functions.upload-to-cloudinary]
verify_jwt = false

[functions.analyze-brand]
verify_jwt = false
