project_id = "esrimjavbjdtecszxudc"

[api]
enabled = true

[functions.analyze-email-design]
verify_jwt = false

[functions.upload-to-cloudinary]
verify_jwt = false

[functions.analyze-brand]
verify_jwt = false

[functions.push-to-klaviyo]
verify_jwt = false

[functions.analyze-slices]
verify_jwt = false

[functions.generate-slice-html]
verify_jwt = false

[functions.refine-slice-html]
verify_jwt = false

[functions.refine-campaign]
verify_jwt = false

[functions.generate-footer-html]
verify_jwt = false
